apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekscluster
  region: ap-south-1

nodeGroups:
   - name: ng1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: mykey5202
   - name: ng2
     desiredCapacity: 1
     instanceType: t2.micro
     ssh:
        publicKeyName: mykey5202
